### ISSUE TITLE
hello ,can you help me  ,i have a problem .

### ISSUE THREAD

**Issue by bailiangze** [zhr1201/CNN-for-single-channel-speech-enhancement#12]
it occurs when i use your code .it likes below
Exception in thread Thread-7:
Traceback (most recent call last):
  File "E:\anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\anaconda\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\deeplearning\CNN-for-single-channel-speech-enhancement-master\audio_reader.py", line 108, in thread_main
    noise_org, _ = librosa.load(self.noisefiles[noise_id], sr=None)
  File "E:\anaconda\lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "E:\anaconda\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

but i test the code l'ibrosa; it does not have problem。can you give me some advice

**Comment by bailiangze** [comment]
Who can help me .i am confused with this problem

**Comment by ffxz** [comment]
@bailiangze it might be the problem of *.wav file, the timit wav format is different from other. you can try some other wav or use audition software change the format.
