### ISSUE TITLE
你好,我在训练网络中遇到如下问题,可以帮我看看么?

### ISSUE THREAD

**Issue by Lerry123** [zhr1201/CNN-for-single-channel-speech-enhancement#22]
usr/local/lib/python2.7/dist-packages/librosa/init.py:35: FutureWarning: You are using librosa with Python 2. Please note that librosa 0.7 will be the last version to support Python 2, after which it will require Python 3 or later.
FutureWarning)
11572 speech found
11572 noise found
824 speech found
824 noise found
Traceback (most recent call last):
File "SENN_train.py", line 191, in
train()
File "SENN_train.py", line 122, in train
sess.run(init)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
run_metadata_ptr)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
feed_dict_string, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
target_list, options, run_metadata)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
raise type(e)(node_def, op, message)
InvalidArgumentError: No OpKernel was registered to support Op 'FFT' with these attrs. Registered kernels:

     [[Node: FFT_1 = FFT[](Cast_1)]]

Caused by op u'FFT_1', defined at:
File "SENN_train.py", line 191, in
train()
File "SENN_train.py", line 105, in train
images, targets = SE_Net.inputs(data_frames)
File "SENN.py", line 98, in inputs
speech_f0 = tf.fft(tf.cast(raw_speech, tf.complex64))
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 798, in fft
result = _op_def_lib.apply_op("FFT", input=input, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in init
self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FFT' with these attrs. Registered kernels:

     [[Node: FFT_1 = FFT[](Cast_1)]]

**Comment by Lerry123** [comment]
这个问题我解决了,训练时又出现这个问题:
IOError: [Errno 2] No such file or directory: 'p269_096.wav'
这个文件还是一直在变,每次都不一样,程序报错但一直不结束这是为什么

**Comment by Lerry123** [comment]
你好不好意思打扰您了,您这个是将噪音与语音进行汇合成不同的信噪比吗?我这个库是已经加噪后的但是信噪比不知道,对于这个还能用吗?

**Comment by zhr1201** [comment]
应该不能用已经混合好的。运行问题就不是很清楚了，我目前也没有跑这个版本的环境，

**Comment by Lerry123** [comment]
@zhr1201 谢谢您

**Comment by ZBang** [comment]
请问一般要训练多久啊？
