### ISSUE TITLE
The loss can not decrese

### ISSUE THREAD

**Issue by zyy-fc** [zhr1201/CNN-for-single-channel-speech-enhancement#9]
Thank you for sharing!
I used the 4620 utterances from the training set of the TIMIT corpus as  train set, and 119 types noise as train set. Besides, the 10 utterances from the test set of the TIMIT corpus and other 10 types noise as validation set. I have trained this model for more than 10 hours, but the loss seems to be  invariant. 
I do not know why. I will be honoured if you help me.
![a](https://user-images.githubusercontent.com/32134929/47974483-c8278a80-e0e4-11e8-8432-75897c95494a.png)

**Comment by zhr1201** [comment]
I think it would be better if you could use some kind of plot (e.g. tensorboard ) to visualize the convergence and test some samples, also try to do some parameter tunning. If the model still couldn't generate satisfactory samples, probably adding more layers and use more advance structures may help.

**Comment by zyy-fc** [comment]
than you very much!

**Comment by yuanyuan0209** [comment]
But I have the following problems when I run the code 'SENN_audio_eval.py'.  I appreciate it if you could help me.
![1](https://user-images.githubusercontent.com/32134929/48106972-af4fde00-e278-11e8-92ee-8ad4feb3c478.png)

**Comment by yuanyuan0209** [comment]
But I am also having another problem and want to ask if you solved it. I have tried different approaches but all to no available
![a1](https://user-images.githubusercontent.com/32134929/48108430-0dcb8b00-e27e-11e8-9d1a-9ba13fcbce8c.png)
.

**Comment by zhr1201** [comment]
Not sure what the problem is, I guess it is very likely becaues of version issues. You can set a stop at stft to see what is going wrong.


On 11/07/2018 11:12, yuanyuan0209 wrote:

But I am also having another problem and want to ask if you solved it. I have tried different approaches but all to no available

.

**Comment by bailiangze** [comment]
it occurs when i use your code .it likes below
Exception in thread Thread-7:
Traceback (most recent call last):
File "E:\anaconda\lib\threading.py", line 916, in _bootstrap_inner
self.run()
File "E:\anaconda\lib\threading.py", line 864, in run
self._target(*self._args, **self.kwargs)
File "D:\deeplearning\CNN-for-single-channel-speech-enhancement-master\audio_reader.py", line 108, in thread_main
noise_org, _ = librosa.load(self.noisefiles[noise_id], sr=None)
File "E:\anaconda\lib\site-packages\librosa\core\audio.py", line 112, in load
with audioread.audio_open(os.path.realpath(path)) as input_file:
File "E:\anaconda\lib\site-packages\audioread_init.py", line 116, in audio_open
raise NoBackendError()
audioread.NoBackendError

but i test the code l'ibrosa; it does not have problem。can you give me some advice

**Comment by ffxz** [comment]
@yuanyuan0209 is your loss is decreased? can your share your successful results?

**Comment by lvyilan23** [comment]
> @yuanyuan0209 is your loss is decreased? can your share your successful results?

hi, have you solve the problem? I meet the same question

**Comment by ZBang** [comment]
I meet the same problem.
if you hava some ideas,please tell me
thanks!

**Comment by lvyilan23** [comment]
i have no idea, so I changed the code to reproduce the model



发自我的&nbsp;iPad


------------------ Original ------------------
